function MSSlogbook4matlab = importMSSlogbook4matlab(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MSSLOGBOOK4MATLAB = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  MSSLOGBOOK4MATLAB = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  MSSlogbook4matlab = importfile("/Volumes/legwork/scientific_work_areas/oceanography/MSS34/MSS_logbook_4matlab.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Aug-2026 00:59:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Latitude_dd", "Longitude_dd", "DepthEA640_m", "MSSstation", "EventNumber", "MSScast", "TargetDepth_m", "EventActionBuiltInString", "Comment", "Use"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "categorical", "char", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Comment", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["EventActionBuiltInString", "Comment"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Time", "InputFormat", "MM/dd/yy HH:mm", "DatetimeFormat", "preserveinput");

% Import the data
MSSlogbook4matlab = readtable(filename, opts);

end