%SET_UNDERWAY_PARAMS Set up underway variable names for the current cruise
%
%   Sets the variable names used for underway processing. These structures 
%   should be flexible to accommodate a wide range of RVDAS configurations.
%
%   This particular script is set up for RRS Sir David Attenborough
%
%   version 1.1 - 20230119 - Povl Abrahamsen, DY158 - initial version for SDA
%   version 1.2 - 20240712 - Kat Turner, SD033.
%     Povl Abrahamsen has commented out addition of prefix to tables variables
%   version 1.3 - 20240919 - Bryony Freer and Povl Abrahamsen, SD041

cruisename='sd063';
cruise_rvdas_prefix=''; %[cruisename,'_']; % if using a cruise-specific view!

cruise_netcdf_metadata=struct(...
    'platform_type','ship',...
    'platform_identifier','RRS Sir David Attenborough',...
    'title','Underway dataset from cruise SD063',...
    'institution','British Antarctic Survey',...
    'source','observation',...
    'references','Cruise report at https://www.bodc.ac.uk/resources/inventories/cruise_inventory/report/SD063.pdf',...
    'history',sprintf('Generated on %s at %s','RRS Sir David Attenborough',datetime('now'))...
    );

% tables to be loaded into the rvdas_listit code. These will be saved into
% the nav directory
nav_tables={'gnss_kongsberg_seapath_320_port1_ingga','gnss_kongsberg_seapath_320_port1_invtg',...
    'attitude_kongsberg_seapath_320_heading_port1_inhdt','attitude_kongsberg_seapath_320_motion_port1_kmatt',...
    'gnss_kongsberg_seapath_320_stbd1_ingga','gnss_kongsberg_seapath_320_stbd1_invtg',...
    'attitude_kongsberg_seapath_320_heading_stbd1_inhdt','attitude_kongsberg_seapath_320_motion_stbd1_kmatt',...
    'attitude_ixblue_phins_surface_heading_crp1_hehdt','attitude_ixblue_phins_surface_motion_crp1_kmatt'};

% nav_tables={...
%    'attitude_raytheon_standard_30mf_port1_hehdt','attitude_raytheon_standard_30mf_stbd1_hehdt'};

% if there is a view add this before
% for n=1:length(nav_tables)
%     nav_tables{n}=[cruise_rvdas_prefix,nav_tables{n}];
% end

nav_convert_positions=true; % convert positions from DDMMM.mmm to DDD.ddd
    % this should be set to "false" on ships where RVDAS does the
    % conversion before we do (e.g. Discovery)!

% the sensorlist is useful for the plot scripts
nav_sensor_sets=[...
    struct('set_name','SeaPath 1',...        % RRS Sir David Attenborough SeaPath 320
        'gga_table',[cruise_rvdas_prefix,'gnss_kongsberg_seapath_320_port1_ingga'],... % GGA contains latitude and longitude
            'gga_lat_field','latitude',...
            'gga_lon_field','longitude',...
        'vtg_table',[cruise_rvdas_prefix,'gnss_kongsberg_seapath_320_port1_invtg'],... % VTG contains course/speed over ground
            'vtg_cog_field','courseoverground',...
            'vtg_sog_field','speedknots',...
        'hdt_table',[cruise_rvdas_prefix,'attitude_kongsberg_seapath_320_heading_port1_inhdt'],...      % HDT contains true heading
            'hdt_hdg_field','headingtrue',...
        'file_add','_seapath1'),...     
    struct('set_name','SeaPath 2',...        % RRS Sir David Attenborough SeaPath 320
        'gga_table',[cruise_rvdas_prefix,'gnss_kongsberg_seapath_320_stbd1_ingga'],... % GGA contains latitude and longitude
            'gga_lat_field','latitude',...
            'gga_lon_field','longitude',...
        'vtg_table',[cruise_rvdas_prefix,'gnss_kongsberg_seapath_320_stbd1_invtg'],... % VTG contains course/speed over ground
            'vtg_cog_field','courseoverground',...
            'vtg_sog_field','speedknots',...
        'hdt_table',[cruise_rvdas_prefix,'attitude_kongsberg_seapath_320_heading_stbd1_inhdt'],...      % HDT contains true heading
            'hdt_hdg_field','headingtrue',...
        'file_add','_seapath2')...     
    ];

nav_sensor_set_best=1; % our main nav dataset - SeaPath port

hpr_sensor_sets=[...
    struct('set_name','SeaPath 1',...
        'hpr_table',[cruise_rvdas_prefix,'attitude_kongsberg_seapath_320_motion_port1_kmatt'],...
            'hpr_heading_field','heading',...
            'hpr_heave_field','heave','hpr_heave_orientation','up',...
            'hpr_pitch_field','pitch','hpr_pitch_orientation','fore_up',...
            'hpr_roll_field','roll','hpr_roll_orientation','starboard_down',...
            'hpr_scale_factor',0.01, ...
            'file_add','_seapath1'),...
    struct('set_name','SeaPath 2',...
        'hpr_table',[cruise_rvdas_prefix,'attitude_kongsberg_seapath_320_motion_stbd1_kmatt'],...
            'hpr_heading_field','heading',...
            'hpr_heave_field','heave','hpr_heave_orientation','up',...
            'hpr_pitch_field','pitch','hpr_pitch_orientation','fore_up',...
            'hpr_roll_field','roll','hpr_roll_orientation','starboard_down',...
            'hpr_scale_factor',0.01, ...
            'file_add','_seapath2'),...
    struct('set_name','Phins',...
        'hpr_table',[cruise_rvdas_prefix,'attitude_ixblue_phins_surface_motion_crp1_kmatt'],...
            'hpr_heading_field','heading',...
            'hpr_heave_field','heave','hpr_heave_orientation','up',... % double-check this!!!
            'hpr_pitch_field','pitch','hpr_pitch_orientation','fore_up',... % double-check this!!!
            'hpr_roll_field','roll','hpr_roll_orientation','starboard_down',...
            'hpr_scale_factor',0.01, ...
            'file_add','_phinns'),... % double-check this!!!
    ];

% struct('set_name','Ratheon 1',...
%         'hpr_table',[cruise_rvdas_prefix,'attitude_raytheon_standard_30mf_port1_hehdt'],...
%             'hpr_heading_field','headingtrue',...
%             'hpr_heave_field','','hpr_heave_orientation','',... % couldn't find these for the ratheon dataset
%             'hpr_pitch_field','','hpr_pitch_orientation','',... % couldn't find these for the ratheon dataset
%             'hpr_roll_field','','hpr_roll_orientation','',...
%             'hpr_scale_factor',1),... % double-check this!!!
%      struct('set_name','Ratheon 2',...
%         'hpr_table',[cruise_rvdas_prefix,'attitude_raytheon_standard_30mf_stbd1_hehdt'],...
%             'hpr_heading_field','headingtrue',...
%             'hpr_heave_field','','hpr_heave_orientation','',... 
%             'hpr_pitch_field','','hpr_pitch_orientation','',... 
%             'hpr_roll_field','','hpr_roll_orientation','',...
%             'hpr_scale_factor',1),... 

% same as above but for loading the ocean dataset
ocl_tables={'flowmeter_litremeter_lmx24_ucsw1_plmflow1','thermometer_seabird_sbe38_ucsw1_psbsst1', ...
            'thermometer_seabird_sbe38_ucsw2_psbsst1','radiometer_heitronics_ct15_85_stbd1_phsst',...
            'radiometer_heitronics_ct15_85_port1_phsst','thermosalinograph_seabird_sbe45_ucsw1_psbtsg1', ...
            'soundvelocity_valeport_minisvs_ucsw1_pvsv1','fluorometer_wetlabs_wschl_ucsw1_pwlfluor1', ...
            'transmissometer_wetlabs_cstar_ucsw1_pwltran1','met_vaisala_hmp155e_scimast1_pvtnh2', ...
            'met_vaisala_hmp155e_scimast2_pvtnh2','met_michell_optidew2_aerosol1_pmdew1',...
            'met_vaisala_ptb330_v2_aerosol1_pvbar','met_vaisala_ptb330_v2_aerosol2_pvbar',...
            'radiometer_kipp_zonen_smp22_scimast1_pkpyran','radiometer_kipp_zonen_smp22_foremast1_pkpyran', ...
            'anemometer_ft_tech_ft702lt_centremast1_wimwv','anemometer_observator_omc116_portmast1_wimwv', ...
            'anemometer_observator_omc116_stbdmast1_wimwv','met_vaisala_hmp155e_foremast1_pvtnh2', ...
            'radiometer_satlantic_par_foremast1_pspar','radiometer_satlantic_par_scimast1_pspar', ...
            };

% the fields in ocl_sensors are:
%   1: RVDAS table
%   2: RVDAS variable name
%   3: our (short) variable name for Matlab and NetCDF file
%   4: units
%   5: long/display variable name
%   6: CF standard variable name
%   7: calibration function for uncalibrated sensors
% for example: 
% 'var_name',{{{RVDAS table, RVDAS variable name, short name, units, long
%             name, CF variable neame, calibreation}}}

ocl_sensors=struct(...
    'ocl_flow',{{{[cruise_rvdas_prefix,'flowmeter_litremeter_lmx24_ucsw1_plmflow1'], ...
                'flowrate','flow','L min-1','TSG flow rate','flowrate',@(x) x./1000}}},...
    'ocl_water_temp',{{ ...
                    {[cruise_rvdas_prefix,'thermosalinograph_seabird_sbe45_ucsw1_psbtsg1'], ...
                    'temperature','tstemperature','Celsius',...
                    'thermosalinograph temperature','temperature_of_analysis_of_sea_water',[]},...
                    {[cruise_rvdas_prefix,'thermometer_seabird_sbe38_ucsw1_psbsst1'],...
                    'temperature','temp1','Celsius',...
                    'underway temperature 1','sea_surface_temperature',[]},...
                    {[cruise_rvdas_prefix,'thermometer_seabird_sbe38_ucsw2_psbsst1'],...
                    'temperature','temp2','Celsius',...
                    'underway temperature 2','sea_surface_temperature',[]},...
                    {[cruise_rvdas_prefix,'radiometer_heitronics_ct15_85_stbd1_phsst'],...
                    'seasurfacetemperature','irtemp1','Celsius',...
                    'infrared temperature starboard','sea_surface_temperature',[]},...
                    {[cruise_rvdas_prefix,'radiometer_heitronics_ct15_85_port1_phsst'],...
                    'seasurfacetemperature','irtemp2','Celsius',...
                    'infrared temperature port','sea_surface_temperature',[]},...
                   }},...
    'ocl_water_cond',{{{[cruise_rvdas_prefix,'thermosalinograph_seabird_sbe45_ucsw1_psbtsg1'], ...
                    'conductivity','cond','mS cm-1','SBE45 conductivity','',[]}}},...
    'ocl_water_sal',{{{[cruise_rvdas_prefix,'thermosalinograph_seabird_sbe45_ucsw1_psbtsg1'], ...
                    'salinity','salin','1','SBE45 salinity','sea_surface_salinity',[]}}},...
    'ocl_water_svel',{{{[cruise_rvdas_prefix,'soundvelocity_valeport_minisvs_ucsw1_pvsv1'],...
                    'soundvelocity','svel','m s-1','Valeport MiniSVS sound velocity','',[]}}},...
    'ocl_water_fluor',{{{[cruise_rvdas_prefix,'fluorometer_wetlabs_wschl_ucsw1_pwlfluor1'], ...
                    'chlorophyll','fluor','mg m-3','Chlorophyll A fluorescence','mass_concentration_of_chlorophyll_a_in_sea_water',...
                     @(x) (x-53).*0.0190}}},... % WETStar s/n WSCHL-1498 14/02/2025, 2017 calibration certificate for s/n 1498 sensor swapped back in before 2024/25 season 
    'ocl_water_trans',{{{[cruise_rvdas_prefix,'transmissometer_wetlabs_cstar_ucsw1_pwltran1'], ...
                    'calculatedbeam','trans','percent','beam transmittance through 25 cm of seawater',...
                     @(x) exp(x.*0.25).*100}}},... % calculation to transmittance from beam attenuation factor, previous calculation was: @(x) x./15401.*100}}},... % C-STAR s/n CST-1505DR 16/08/2023
    'ocl_air_temp',{{ ...
                    {[cruise_rvdas_prefix,'met_vaisala_hmp155e_scimast1_pvtnh2'], ...
                    'airtemperature','airtemp1','Celcius','air temperature scimast 1',[]},...
                    {[cruise_rvdas_prefix,'met_vaisala_hmp155e_scimast2_pvtnh2'], ...
                    'airtemperature','airtemp2','Celcius','air temperature scimast 2',[]}}},...
    'ocl_air_rel_hum',{{ ...
                    {[cruise_rvdas_prefix,'met_michell_optidew2_aerosol1_pmdew1'],...
                    'relativehumidity','humidity1','percent','relative humidity aerosol 1',[]}, ...
                    {[cruise_rvdas_prefix,'met_vaisala_hmp155e_foremast1_pvtnh2'],...
                    'relativehumidity','humidity2','percent','relative humidity aerosol 2',[]}, ...
                    {[cruise_rvdas_prefix,'met_vaisala_hmp155e_scimast1_pvtnh2'],...
                    'relativehumidity','humidity3','percent','relative humidity scimast 1',[]}, ...
                    {[cruise_rvdas_prefix,'met_vaisala_hmp155e_scimast2_pvtnh2'],...
                    'relativehumidity','humidity4','percent','relative humidity scimast 2',[]}, ...
                    }},...
    'ocl_air_pressure',{{ ...
                    {[cruise_rvdas_prefix,'met_vaisala_ptb330_v2_aerosol1_pvbar'],...
                    'airpressure','airpressure1','hPa',...
                    'air pressure at MSL aerosol1',[]} ...
                    {[cruise_rvdas_prefix,'met_vaisala_ptb330_v2_aerosol2_pvbar'],...
                    'airpressure','airpressure2','hPa',...
                    'air pressure at MSL aerosol2',[]} ...
                    }},...
    'ocl_rad_tir',{{ ...
                    {[cruise_rvdas_prefix,'radiometer_kipp_zonen_smp22_scimast1_pkpyran'], ...
                    'shortwaveradiationcorrected','tirscimast','W m-2','TIR scimast',...
                    'downwelling_shortwave_flux_in_air',[]},...
                    {[cruise_rvdas_prefix,'radiometer_kipp_zonen_smp22_foremast1_pkpyran'], ...
                    'shortwaveradiationcorrected','tirforemast','W m-2','TIR foremast',...
                    'downwelling_shortwave_flux_in_air',[]}}},...
    'ocl_wind_rel_speed',{{ ...
                    {[cruise_rvdas_prefix,'anemometer_ft_tech_ft702lt_centremast1_wimwv'], ...
                    'windspeed','windspeed_rel_centremast','m s-1','relative wind speed',[]} ...
                    {[cruise_rvdas_prefix,'anemometer_observator_omc116_portmast1_wimwv'], ...
                    'windspeed','windspeed_rel_portmast','m s-1','relative wind speed',[]} ...
                    {[cruise_rvdas_prefix,'anemometer_observator_omc116_stbdmast1_wimwv'], ...
                    'windspeed','windspeed_rel_stbmast','m s-1','relative wind speed',[]}}},...
    'ocl_wind_rel_dir',{{ ...
                    {[cruise_rvdas_prefix,'anemometer_ft_tech_ft702lt_centremast1_wimwv'], ...
                    'winddirection','winddir_rel_centremast','degree','relative wind direction centremast',[]} ...
                    {[cruise_rvdas_prefix,'anemometer_observator_omc116_portmast1_wimwv'], ...
                    'winddirection','winddir_rel_portmast','degree','relative wind direction port',[]} ...
                    {[cruise_rvdas_prefix,'anemometer_observator_omc116_stbdmast1_wimwv'], ...
                    'winddirection','winddir_rel_stbmast','degree','relative wind direction scimast',[]}}}, ...
    'ocl_rad_par',{{ ...
                    {[cruise_rvdas_prefix,'radiometer_satlantic_par_foremast1_pspar'], ...
                    'par','parforemast','umol m-2 s-1','PAR foremast',...
                    'surface_downwelling_photosynthetic_photon_flux_in_air',[]},...
                     {[cruise_rvdas_prefix,'radiometer_satlantic_par_scimast1_pspar'], ...
                    'par','parscimast','umol m-2 s-1','PAR scimast',...
                    'surface_downwelling_photosynthetic_photon_flux_in_air',[]},...
                     }});

ocl_calc_std=['trans','svel'];

ocl_calc_true_wind=true;
ocl_true_wind_names={{'windspeed_abs_centremast','winddir_abs_centremast','wind_u_abs_centremast','wind_v_abs_centremast'},...
    {'windspeed_abs_portmast','winddir_abs_portmast','wind_u_abs_portmast','wind_v_abs_portmast'},...
    {'windspeed_abs_stbmast','winddir_abs_stbmast','wind_u_abs_stbmast','wind_v_abs_stbmast'}};

bathy_tables={[cruise_rvdas_prefix,'singlebeam_kongsberg_ea640_hull1_dbdbt'],...
    [cruise_rvdas_prefix,'multibeam_kongsberg_em124_hull1_kcdpt'],...
    [cruise_rvdas_prefix,'multibeam_kongsberg_em712_hull1_kodpt']};

bathy_sensor_sets=[...
    struct('set_name','ea640',...
        'set_name_long','EA640 singlebeam',...
        'bathy_table',[cruise_rvdas_prefix,'singlebeam_kongsberg_ea640_hull1_dbdbt'],...
            'depth_below_surface_field','',...
            'depth_below_transducer_field','waterdepthmeterfromtransducer',...
            'transducer_offset_field','',...
            'fixed_transducer_offset',6.5,...
            'depth_is_uncorrected',true),...
    struct('set_name','em124',...
        'set_name_long','EM124 multibeam',...
        'bathy_table',[cruise_rvdas_prefix,'multibeam_kongsberg_em124_hull1_kcdpt'],...
            'depth_below_surface_field','',...
            'depth_below_transducer_field','waterdepthmeterfromtransducer',...
            'transducer_offset_field','offsetmeterfromtransducer',...
            'fixed_transducer_offset',[],...
            'depth_is_uncorrected',false),...
    struct('set_name','em712',...
        'set_name_long','EM712 multibeam',...
        'bathy_table',[cruise_rvdas_prefix,'multibeam_kongsberg_em712_hull1_kodpt'],...
            'depth_below_surface_field','',...
            'depth_below_transducer_field','waterdepthmeterfromtransducer',...
            'transducer_offset_field','offsetmeterfromtransducer',...
            'fixed_transducer_offset',[],...
            'depth_is_uncorrected',false),...
    ];
